default:
    rules:
        cyclomaticComplexity: [ 10, 9, 5 ]
        maintainabilityIndex: [ 1, 2, 99 ]

    failure: average.maintainabilityIndex < 50 or sum.loc > 10000

    path:
        directory: src
        extensions: php
        exclude: test

    logging:
        report:
            xml:    ./_log/phpmetrics.xml
            html:   ./_log/phpmetrics.html
            csv:    ./_log/phpmetrics.csv
        violations:
            xml:    ./_log/violations.xml
        chart:
            bubbles: ./_log/bubbles.svg
